//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18444
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodMood {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoodMood.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The application has been upgraded.
        /// </summary>
        internal static string ApplicaionUpgraded {
            get {
                return ResourceManager.GetString("ApplicaionUpgraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A restart is required..
        /// </summary>
        internal static string ApplicaionUpgradedMessage {
            get {
                return ResourceManager.GetString("ApplicaionUpgradedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Restart.
        /// </summary>
        internal static string ApplicationUpgradedButtonText {
            get {
                return ResourceManager.GetString("ApplicationUpgradedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please check your Internet Connection....
        /// </summary>
        internal static string CheckYourInternetConnection {
            get {
                return ResourceManager.GetString("CheckYourInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Download failed..
        /// </summary>
        internal static string DowloadFailed {
            get {
                return ResourceManager.GetString("DowloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please check your network connection, or try again later. Error: {0}.
        /// </summary>
        internal static string DowloadFailedMessage {
            get {
                return ResourceManager.GetString("DowloadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ex argument required.
        /// </summary>
        internal static string ExArgumentRequired {
            get {
                return ResourceManager.GetString("ExArgumentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Go To {0} site....
        /// </summary>
        internal static string GoToProviderWebSite {
            get {
                return ResourceManager.GetString("GoToProviderWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mandatory update..
        /// </summary>
        internal static string MandatoryUpdate {
            get {
                return ResourceManager.GetString("MandatoryUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An update is required from your current version to version {0}. The application will now install the update and restart..
        /// </summary>
        internal static string MandatoryUpdateMessage {
            get {
                return ResourceManager.GetString("MandatoryUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a message argument required.
        /// </summary>
        internal static string MessageArgumentRequired {
            get {
                return ResourceManager.GetString("MessageArgumentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a noButton argument required.
        /// </summary>
        internal static string NoButtonArgumentRequired {
            get {
                return ResourceManager.GetString("NoButtonArgumentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No update available..
        /// </summary>
        internal static string NoUpdate {
            get {
                return ResourceManager.GetString("NoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You are running the latest version :).
        /// </summary>
        internal static string NoUpdateMessage {
            get {
                return ResourceManager.GetString("NoUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a select &apos;refresh&apos; menu&apos; item to update the picture.
        /// </summary>
        internal static string SelectRefreshInfo {
            get {
                return ResourceManager.GetString("SelectRefreshInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        internal static string TrayHideInfo {
            get {
                return ResourceManager.GetString("TrayHideInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An update is available..
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Would you like to update the application now?.
        /// </summary>
        internal static string UpdateAvailableMessage {
            get {
                return ResourceManager.GetString("UpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Update.
        /// </summary>
        internal static string UpdateButtonText {
            get {
                return ResourceManager.GetString("UpdateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Updated check failed..
        /// </summary>
        internal static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The ClickOnce deployment is corrupt. Please redeploy the application and try again. Error: {0}.
        /// </summary>
        internal static string UpdateCheckFailedMessage {
            get {
                return ResourceManager.GetString("UpdateCheckFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a This application cannot be updated..
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a It is likely not a ClickOnce application. Error: {0}.
        /// </summary>
        internal static string UpdateFailedMessage {
            get {
                return ResourceManager.GetString("UpdateFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a updating {0} photo of the day....
        /// </summary>
        internal static string UpdateInProgressInfo {
            get {
                return ResourceManager.GetString("UpdateInProgressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a version {0}.
        /// </summary>
        internal static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot move new downloaded photo to &apos;goodmood_wallpaper.bmp&apos; file.
        /// </summary>
        internal static string WallpaperCopyError {
            get {
                return ResourceManager.GetString("WallpaperCopyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a yesButton  argument required.
        /// </summary>
        internal static string YesButtonArgumentRequired {
            get {
                return ResourceManager.GetString("YesButtonArgumentRequired", resourceCulture);
            }
        }
    }
}
